### ISSUE TITLE
Send feedback in mobile ui - duplicate office names

### ISSUE THREAD

**Issue by mehukatti212** [hep7agon/city-feedback-hub#108]
when i press the "locate me" button the dropdown list shows me two items. When i move the marker and press the "locate me" button again, the number of items in the dropdown list is doubled. If i iterate this, the list just gets bigger and bigger (always by the number of original offices).

![2016-03-17 20 02 55](https://cloud.githubusercontent.com/assets/14871007/13859468/442aee24-ec8c-11e5-8b62-9a9cea1f8c81.png)
![2016-03-17 20 02 46](https://cloud.githubusercontent.com/assets/14871007/13859469/442afe32-ec8c-11e5-9b2f-efc64aa2bb4c.png)

**Comment by mehukatti212** [comment]
Also: is the use case "show me the nearest offices"? If it is, the list view doesnt show offices (=service points) based on where the marker is. It only shows attributes/service points (?) after the user has pressed "locate me"

**Comment by sevesalm** [comment]
The first one is fixed. The second one will be fixed once the whole map system/form is redone.

**Comment by sevesalm** [comment]
Both fixed.
