### ISSUE TITLE
List view - issues with distance

### ISSUE THREAD

**Issue by mehukatti212** [hep7agon/city-feedback-hub#112]
In list view there are feedbacks where the agency responsible is e.g. Kaupunginkanslia and the distance from my home (Niittykumpu) to kaupunginkanslia is 7000 km (images below). 

![2016-03-17 20 22 51](https://cloud.githubusercontent.com/assets/14871007/13859973/d5060468-ec8e-11e5-91f5-bc3e0a0b5e55.png)
![2016-03-17 20 22 56](https://cloud.githubusercontent.com/assets/14871007/13859974/d507a5f2-ec8e-11e5-9c6b-a9b5ff1e0ad9.png)

**Comment by sevesalm** [comment]
This happens when the location field contais "0.000 0.00". So basically somewhere at the "Armpit of Africa". We'll cover this special case.

**Comment by vitalyivanov** [comment]
Now the distance is removing from the feedbacks with zero coordinates.
