### ISSUE TITLE
Statistics page under Virastot too wide

### ISSUE THREAD

**Issue by mehukatti212** [hep7agon/city-feedback-hub#113]
The statistics page under Virastot is too wide. Data should be "put closer". now the user must scroll sideways as well. 

![2016-03-17 20 28 55](https://cloud.githubusercontent.com/assets/14871007/13860160/adb568da-ec8f-11e5-8f75-b4e42e247b15.png)

**Comment by sevesalm** [comment]
I think we don't need all three: total, closed, open. Total + open is enough and I think open is more interesting than closed as agencies really need to quicly see if it is 0 or more. And usually closed is very close to total so it is not easy to see how close: 543423 vs 543419.

**Comment by mehukatti212** [comment]
Has this issue been fixed? Just tested this and there is no change in feedback.hel.ninja.
