### ISSUE TITLE
Statistics page - Kaaviot -> ui needs lots of more effort

### ISSUE THREAD

**Issue by mehukatti212** [hep7agon/city-feedback-hub#114]
The layout for mobile view needs lots of more work. The texts in axis overlap too much.

![2016-03-17 20 30 45](https://cloud.githubusercontent.com/assets/14871007/13860252/0a360f7e-ec90-11e5-9186-90b0160fef81.png)

**Comment by sevesalm** [comment]
Horizontal bars might be a solution.

**Comment by mehukatti212** [comment]
looks better in mobile. Still we need to think a better way to show these charts, because public works department takes too much attention (=virasto kaaviot).

Aika kaaviot needs also some work. Hours should changed to days. The user should instantly understand what the numbers mean  (e.g. 150 hours = 6 days X hours).

**Comment by vitalyivanov** [comment]
Done! Days and hours issue is now in other task.
