### ISSUE TITLE
Map view - number of feedback balloon behind location marker

### ISSUE THREAD

**Issue by mehukatti212** [hep7agon/city-feedback-hub#120]
Map view - number of feedback balloon behind location marker. 

![image](https://cloud.githubusercontent.com/assets/14871007/14104228/b132b2b2-f5ac-11e5-8196-d0bf853d6ceb.png)

**Comment by vitalyivanov** [comment]
What should be fixed here?

**Comment by sevesalm** [comment]
Thr number below the marker is not visible. But Im not sure if there is any good way to fix it as that is kind of a feature... Maybe have the marker jump a bit when mouse cursor hovers on it :)

**Comment by vitalyivanov** [comment]
I think it's by design. Just zoom in to check the amount of feedbacks. Jumping marker is a good idea! But we don't have time to implement it and properly test.
