### ISSUE TITLE
Charts

### ISSUE THREAD

**Issue by Whaith** [hep7agon/city-feedback-hub#122]
- [x] Change Titles to proper Finnish
- [x] Agencies chart is problematic: one bar only shown, others too small
- [x] Change hours to days: axis shows days, and chart shows days + hours if possible
- [x] Chart showing fixing time has bar height problems. Bar height doesn't match the actual value shown. A bar showing (11pv 20h) is taller than the 12pv mark on axis. EDIT: The problem is maybe in the axis marks. The distance from 2 to 3 is equal to distance from 3 to 5.

**Comment by dostumut** [comment]
Spelling mistakes are handled.
You can zoom in out in agency charts so it handles the constrains of small columns.
Hours are changed to days in time chart

**Comment by dostumut** [comment]
Text in charts is fully visible now in mobile version(real estate agency case).

**Comment by dostumut** [comment]
Time chart is fixed and it uses the same format we use in other places. 2pv and 5h

**Comment by dostumut** [comment]
The axis values are redefined and fixed
