### ISSUE TITLE
Detailed feedback

### ISSUE THREAD

**Issue by Whaith** [hep7agon/city-feedback-hub#124]
- [x] Show some answer when City handles the feedback
- [ ]  Show what has been done to the feedback (received, send to a new agency, closed, etc. See Fiksaus Metro - especially). But, only show relevant stuff! 
- [x] Use the same marker for location as in other maps (**Severi**)
- [x] Layout broken (Share button + vote buttons, no gap between map and image) (**Jari**)
- [x] Map broken (Bad request)

**Comment by vitalyivanov** [comment]
Unchecked item moved to Not Implemented Features document
