### ISSUE TITLE
Stat tables

### ISSUE THREAD

**Issue by Whaith** [hep7agon/city-feedback-hub#125]
- [x] Remove total column in mobile
- [x] Footer could be broader (showed white on the edges)
- [x] Add links to agencies (add support for backend) (Vitalii)
- [x]  Total column should be hidden in mobile but visible in desktop - use "hidden-xs" class
- [x] Consider better titles, discuss with team

**Comment by Whaith** [comment]
Footer is fixed by reducing the total column.

**Comment by dostumut** [comment]
Links to columns are added in agency statistic page

**Comment by dostumut** [comment]
Removed total columns from tables in statistic page

**Comment by dostumut** [comment]
total column is invisible in mobile and it is visible for web(agency and service statistic page).

**Comment by dostumut** [comment]
Better words are given
