### ISSUE TITLE
Feedback form map improvements

### ISSUE THREAD

**Issue by sevesalm** [hep7agon/city-feedback-hub#126]
- [x] Remove green marker before drawing new (own location) - now draws multiple
- [x] Highlighting doesn’t disappear sometimes when clicking around
- [x] Pan more to see the balloon text (especially mobile) #127 
- [x] Zooming removes service object selection (**Severi**)
- [x] Zoom in after selecting service object if too far away (**Severi**)
- [x] Date picker causes a console error now in form map step

**Comment by obscurage** [comment]
@sevesalm is this done or still in progress?

**Comment by obscurage** [comment]
Fixed the error of form map step
