### ISSUE TITLE
Form category page improvements

### ISSUE THREAD

**Issue by sevesalm** [hep7agon/city-feedback-hub#130]
- [x] Smaller icons so buttons are shown? Test if needed. (**Severi**)
- [x] Gray the remaining steps in stagebar **(Emma)**
- [x] Broken layout on horizontal mode (footer overlaps, test on mobile?)
- [x] Maybe improve the stagebar still a bit

**Comment by madaian** [comment]
Smaller icons were a pain in the butt to handle, so we could scrap the idea...

Severi: I made some changes and now the icons are a bit smaller.

**Comment by sevesalm** [comment]
I think it could be improved. See, how Amazon does it. i think now it looks a bit odd. Amazon greys following steps, and shows them orange when they are done. And bolds the current stem. Can this be improved?

<img width="569" alt="screen shot 2016-03-31 at 15 59 18" src="https://cloud.githubusercontent.com/assets/3775715/14176427/95bc8f04-f759-11e5-97e3-2e9aca25d012.png">

**Comment by madaian** [comment]
Tried out that amazon-like style, what do you think? (Also added this "selected stuff is blue" thing for some kind of consistency)

<img width="893" alt="nayttokuva 58" src="https://cloud.githubusercontent.com/assets/11146256/14207736/ab9d2fb0-f824-11e5-8edb-45340d798983.png">
