### ISSUE TITLE
Image upload

### ISSUE THREAD

**Issue by oaikonen** [hep7agon/city-feedback-hub#131]
- [x] Feature: remove uploaded image (**Severi**)
- [x] Image size restriction bigger: 10MB (**Severi**)
- [x] Image upload broken after pressing next (+back) - DEBUG=False is the reason. 
- [x] Mention the possibility to use camera (**Severi**)
- [x] Translation to Finnish (**Severi**)
- [x] Show correct filename in preview images (when going back) (**Severi**)
- [x] Show correct filesize in preview images (when going back) (**Severi**)

**Comment by vitalyivanov** [comment]
"Image upload broken after pressing next (+back) - DEBUG=False is the reason" moved to not implemented list.
