### ISSUE TITLE
As a user I want to see feedbacks filtered by different criteria on a map

### ISSUE THREAD

**Issue by oaikonen** [hep7agon/city-feedback-hub#17]
E.g.
- open or closed feedback
- based agency responsible
- date (e.g. from calendar: start and end date)
- aspa status notes (in progress, fixed, etc.)
- owner_name
- etc.

Acceptance criteria:
1. Filter feedbacks based on categorization opportunities (open, closed, in progress, owner, etc.)
2. Feedbacks are updated on a map 
3. User can switch between maps (e.g. http://palvelukartta.hel.fi/, openstreet map, earth map, and detailed map for employees city of helsinki )

**Comment by vitalyivanov** [comment]
The initial filters were changed. The only one map is available for now.
