### ISSUE TITLE
Heatmap visualization of open or closed feedback items

### ISSUE THREAD

**Issue by oaikonen** [hep7agon/city-feedback-hub#19]
As a user I want to see a heatmap visualization of open or closed feedback items so that I know where things are looking HOT.

Acceptance criteria:
1. user defines what feedbacks he or she wants to see (open, closed or both) 
2. based on users settings the map is updated with details (=heatmap)

Bugs/todo:
- [x] Overlay buttons don't work with iPhone
- [x] Add filter by agency_responsible - needs API support

**Comment by obscurage** [comment]
Heatmap now updated based on the filter.
