### ISSUE TITLE
Get information about estimation of fixing

### ISSUE THREAD

**Issue by vitalyivanov** [hep7agon/city-feedback-hub#24]
As a resident I want to get information about estimation of fixing so that I can know how long it usually takes to fix the similar problem.

Estimation: how long it takes based on history, how many similar feedbacks were closed.
Feedback status list: http://dev.hel.fi/apis/open311/#Extensions

Acceptance criteria:
1. user send information about a problem
2. after the sending user sees the information about estimation if she provides information about service name 
3. estimation data is attached to feedback and can be seen in detailed feedback views
4. estimation data should be visible in the feedback list (final decision will be made after UX research)

**Comment by obscurage** [comment]
Implemented! Thus, closing the item.
