### ISSUE TITLE
As a user I want to give a "thumbs up" to an existing feedback item.

### ISSUE THREAD

**Issue by oaikonen** [hep7agon/city-feedback-hub#3]
After having seen all the nearest feedback items in the feedback listing,
the user might find the issue that he would have otherwise created a new feedback
item for, but because the user sees this has already been done, he just wants
to qucikly give his support and communicate that he would too like to see this
fixed.

**Comment by vitalyivanov** [comment]
Now it's possible to thumb up the feedbacks from feedback list, feedback details page and from first step of the wizard where the closest feedbacks are shown.
