### ISSUE TITLE
Create step 1 of Feedback Form

### ISSUE THREAD

**Issue by obscurage** [hep7agon/city-feedback-hub#46]
- [x] show the map with existing open feedbacks (Helsinki Center)
- [x] create a button to allow current location placement
- [x] show the information about feedback when user clicks on it

**Comment by obscurage** [comment]
Done.
User can point his/her location.
Lat and lng are inserted to hidden fields as value, which are then passed forwards.

**Comment by obscurage** [comment]
Next: add geolocation and existing feedback in close range.

**Comment by vitalyivanov** [comment]
The task was updated. Map feature is delayed. Let's start with a list.

**Comment by obscurage** [comment]
Map feature back in business.

Later on, try to create map dragging instead of marker placing:
https://maptionnaire.com/fi/776/

**Comment by vitalyivanov** [comment]
Usability will be improved later.
