### ISSUE TITLE
Create list of feedback to Feedback Wizard step 1

### ISSUE THREAD

**Issue by obscurage** [hep7agon/city-feedback-hub#49]
Add a list of feedback that are nearby the user's location.

Map and list should be in the same row.
Map should stay on the left side and take some 70% of the width (on normal/wide screen)
Feedbacklist should stay on the right side and take the rest of the width.

Responsivity needs to be considered.

**Comment by vitalyivanov** [comment]
Duplicates #46. The initial idea of layout was changed.
