### ISSUE TITLE
Work task - migrating POST request features to Django

### ISSUE THREAD

**Issue by IgorDeedsDirtCheap** [hep7agon/city-feedback-hub#54]
Add couple files, no noticeable edits to existing content needed.

**Comment by IgorDeedsDirtCheap** [comment]
On hold, waiting for a review at the previous repo and trying to avoid merge conflicts.

**Comment by vitalyivanov** [comment]
Synchronization with Open311 implemented as an additional Django command based on the logic from Flask solution. POST request will be implemented with Django REST Framework. 
The task can be closed without additional merging. Everything is ok!
