### ISSUE TITLE
Send email to user when the status is changed

### ISSUE THREAD

**Issue by vitalyivanov** [hep7agon/city-feedback-hub#69]
send email to the user when the status of feedback is changed (after synchronization with Open311)

**Comment by madaian** [comment]
Here's the base for the email:

> Hei!
> Helsingin kaupungin City Feedback Hub -palautejärjestelmään antamasi palautteen tila on muuttunut. Voit nähdä palautteen ja tarkastella muutoksia klikkaamalla alla olevaa linkkiä.
> 
> {{ feedback URL }}
> 
> Ystävällisin terveisin,
> City Feedback Hub
> 
> Huom! Älä vastaa tähän viestiin, sillä vastausviestejä ei käsitellä.

**Comment by vitalyivanov** [comment]
![email_notification](https://cloud.githubusercontent.com/assets/1015139/14403044/8cd49118-fe50-11e5-9f52-186690dc3451.png)

The subject is: City Feedback Hub - Request Status Update
Subject and body can be easily changed in the Django settings file. 

To turn on email notification the setting SEND_STATUS_UPDATE_NOTIFICATIONS should be True and real email server settings should be used (EMAIL_HOST, EMAIL_PORT, EMAIL_HOST_USER, EMAIL_HOST_PASSWORD and EMAIL_USE_TLS)
