### ISSUE TITLE
ASPA feedbakcs that are open in ASPA and closed in Feedback system should be open in UI

### ISSUE THREAD

**Issue by mehukatti212** [hep7agon/city-feedback-hub#84]
ASPA feedbakcs that are open in ASPA and closed in Feedback system should be open in UI

If the extended (ASPA) status is public_works_ new/in_progress/completed_scheduled_later, then on UI the feedback should be forced to open. If the ASPA value is completed/completed_requires_no_action, then on UI it can also be set as closed.

**Comment by sevesalm** [comment]
Status is now shown correctly but filtering is now done only using status field. Not with detailed_status stuff.
