### ISSUE TITLE
Give feedback form - enhacements

### ISSUE THREAD

**Issue by mehukatti212** [hep7agon/city-feedback-hub#90]
- [x] if the user has already given permission to follow (location), then the map should focus around the user
- [x] show feedbacks open + closed: have them in different colors (Open = X color, Closed = Y color)  (**Samuli**)
- [x] Update legends to match marker colours
- [ ] _Show feedbacks with status In progress with "Z color" (different than open or closed)_ -> Requires "In progress" status, will not be implemented now
- [ ] _Show the closed feedbacks from the previous 2 weeks_ -> would require more queries, will not be implemented now
- [x] integration with service point registry API
- [ ] <del>I think we also agreed that there should be some kind of list of feedbacks (?)</del> (This would be a new feature, will not be implemented for now)

![give feedback](https://cloud.githubusercontent.com/assets/14871007/13774575/62f99d86-eaa8-11e5-9ff9-8f21faaa8d3e.png)

**Comment by vitalyivanov** [comment]
The peer testing session showed that current UI is convenient. The feedback list on this page could make it overwhelmed. Should we skip it?

**Comment by obscurage** [comment]
I think the listing should be skipped as it is a new feature we'd need to make. Time runs against us and there's no more time for wholly new features, only to enhance existing ones.

What say you @mehukatti212 @tituomin ?

**Comment by mehukatti212** [comment]
Definitely focus on fixing issues etc, not on new features. It would be nice if u vould list (as a result of the project) all the features u didnt have time ti implement. This can partially work as pbl in the long run

**Comment by vitalyivanov** [comment]
Not implemented features are moved to corresponding document in our shared folder.
