### ISSUE TITLE
Mainpage improvements

### ISSUE THREAD

**Issue by sevesalm** [hep7agon/city-feedback-hub#91]
- [x] Truncate titles (**Severi**)
- [x] Same layout for recent and closed feedbacks (**Severi**)
- [x] 1 column for mobile (**Severi**)
- [x] Change the word "ratkaistu" to something else. "käsitelty"? (**Ossi**)
- [x] Change "user count" to "followers" (in Finnish) and provide distinct emai count,, for example. (**Ossi**)
- [x] Replace the background image with something legal
- [x] Make the background image more narrow on mobile (**Severi**)
- [x] 4pv 3h should always be on the same row with all window sizes (**Ossi**)
- [x] Use same empty image placeholder as in feedback list (gray image with scenery) (**Ossi**)
- [x] Same height for all boxes (no matter if there is an image or placeholder, how long title/description...) (**Severi**)
- [x] Same height for all images (no matter if it is an image or placeholder) (**Severi**)
- [x] Tune what info is shown for open or closed feedbacks
- [x] Make images narrower. Now placeholders are 1:1, but maybe 4:3 or 3:2. (**Severi**)
- [x] Show our estimation if the expected_datetime is empty (**Severi**)
- [x] Make service names Finnish even if they are in English in service_name (**Severi**)

More improvements (6.4.2016)
- [x] Should the image/placeholder have some small padding to the top? Looks pretty funny now with left & right paddings.
- [x] The word selection for registered users is now funny: "palautetta antaneita". I.e. the listed amount of people have given the listed amount of feedback. Could consider rephrasing.
- [x] Are colons (kaksoispiste) required in the titles?
- [x] CFH link in the navbar is misleading. Should it be replaced with "Etusivu" or even a home icon?

**Comment by obscurage** [comment]
Should the image/placeholder have some small padding to the top? Looks pretty funny now with left & right paddings,

**Comment by obscurage** [comment]
The word selection for registered users is now funny: "palautetta antaneita". I.e. the listed amount of people have given the listed amount of feedback. Might need to rephrase it!

**Comment by sevesalm** [comment]
I think "CFH" is not misleading. It is in common place and everyone know that clicking left-top corner brings you to the homepage. See the left-top corner of this page for example :smile:

**Comment by obscurage** [comment]
'ait! That was one user feedback I got when I showed the page. But, that is a known decision now, so case is clear!
