### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Whaith** [hep7agon/city-feedback-hub#92]
- [x] API client documentation - at least extra stuff over default Open311
- [x] Comment code at least for relevant trickier parts
- [x] Explain architecture - “2 paragraphs”
- [x] Deployment instructions
- [x] Specification with feature description
- [x] Explain unfinished/non-working features and known defects/shortcomings
- [x] Document custom Django commands

**Comment by vitalyivanov** [comment]
Architecture is explained with the diagram in our project documentation. We can use it.
