### ISSUE TITLE
Improvements to Map page after Sprint 6 Planning

### ISSUE THREAD

**Issue by Whaith** [hep7agon/city-feedback-hub#95]
- [x] Allow clustering in maps
- [x] 2 maps for different use cases (add feedback, feedback browsing)
- [x] Single map page. 
- [x] Translate to Finnish
- [x] Filter options should be real options, not the filter name. Eg. the first option in Services should be "Kaikki", not "Services"?
- [x] Main map should show marker for user location

Notes:
- <del>If time, implement visualisation map for stats page.?? Not decided yet!</del> -> Own/new feature
- Add filter for selecting agency_responsible -> Will be implemented in #129

**Comment by obscurage** [comment]
The following tasks are vague and require discussion:
- If time, implement visualisation map for stats page.?? Not decided yet!
- Add filter for selecting agency_responsible

**Comment by obscurage** [comment]
Mentioned tasks cleared out, this issue regarded as done!
