### ISSUE TITLE
Feedback form map improvements

### ISSUE THREAD

**Issue by sevesalm** [hep7agon/city-feedback-hub#98]
- [x] Popups should work on mobile
- [x] Automatic location detection (**Severi**)
- [x] Automatic centering when location has been fetched (**Severi**)
- [x] Button should just center to user (**Severi**)
- [x] Initial Zoom level closer (ie. more closeup) (**Severi**)
- [x] ~~Switch between map/list IF we implement the list of closest feedbacks~~
- [x] Fix bug when clicking on the map after highlighting a feedback: marker remains highlighted
- [x] If user selects service object, center to that (**Severi**)
- [x] ~~Show service objects as markers?~~ (Didn't work, too much stuff.) (**Severi**)
- [x] Empty selected service_object, if the user moves the marker/map (**Severi**)

**Comment by obscurage** [comment]
Popups fixed for mobile as well.
