### ISSUE TITLE
Separate all Helsinki related stuff

### ISSUE THREAD

**Issue by sevesalm** [hep7agon/city-feedback-hub#99]
Make it possible the deploy to other cities.

**Comment by vitalyivanov** [comment]
At least we should hide service list in feedback form, when ALLOW_HELSINKI_SPECIFIC_FEATURES = False.

**Comment by vitalyivanov** [comment]
Shouldn't be hard. Only Service list on Feedback Form page should be hidden (noticed in Non implemented features document).
